easy_admin:
  entities:
    Category:
        class: App\Entity\Category
        form:
          fields:
            - {property: 'title'}
            - {property: 'description'}

        list:
            fields:
              - {property: 'title', label: 'Titre'}
              - {property: 'content', label: 'Contenu'}
              - {property: 'category', label: 'Catégorie'}
              - {property: 'image', type: 'image'}
              - {property: 'createdAt', label: 'Date'}   

            actions:
              - {name: 'edit', icon: 'pencil', label: false, css_class: 'btn btn-primary'}
              - {name: 'delete', icon: 'trash', label: false, css_class: 'btn btn-danger'}          